ufdPage = {
    "banjo" : "https://ultimateframedata.com/banjo_and_kazooie.php",
    "banjo and kazooie" : "https://ultimateframedata.com/banjo_and_kazooie.php",
    "kazooie" : "https://ultimateframedata.com/banjo_and_kazooie.php",
    "bayo" : "https://ultimateframedata.com/bayonetta.php",
    "bayonetta" : "https://ultimateframedata.com/bayonetta.php",
    "bowser" : "https://ultimateframedata.com/bowser.php",
    "bowser jr." : "https://ultimateframedata.com/bowser_jr.php",
    "jr." : "https://ultimateframedata.com/bowser_jr.php",
    "junior" : "https://ultimateframedata.com/bowser_jr.php",
    "captain falcon" : "https://ultimateframedata.com/captain_falcon.php",
    "falcon" : "https://ultimateframedata.com/captain_falcon.php",
    "chrom" : "https://ultimateframedata.com/chrom.php",
    "cloud" : "https://ultimateframedata.com/cloud.php",
    "corrin" : "https://ultimateframedata.com/corrin.php",
    "daisy" : "https://ultimateframedata.com/daisy.php",
    "dark pit" : "https://ultimateframedata.com/dark_pit.php",
    "dark samus" : "https://ultimateframedata.com/dark_samus.php",
    "diddy kong" : "https://ultimateframedata.com/diddy_kong.php",
    "diddy" : "https://ultimateframedata.com/diddy_kong.php",
    "donkey kong" : "https://ultimateframedata.com/donkey_kong.php",
    "dk" : "https://ultimateframedata.com/donkey_kong.php",
    "dr.mario" : "https://ultimateframedata.com/dr_mario.php",
    "doc" : "https://ultimateframedata.com/dr_mario.php",
    "duck hunt" : "https://ultimateframedata.com/duck_hunt.php",
    "dhd" : "https://ultimateframedata.com/duck_hunt.php",
    "falco" : "https://ultimateframedata.com/falco.php",
    "fox" : "https://ultimateframedata.com/fox.php",
    "ganondorf" : "https://ultimateframedata.com/ganondorf.php",
    "ganon" : "https://ultimateframedata.com/ganondorf.php",
    "greninja" : "https://ultimateframedata.com/greninja.php",
    "gren" : "https://ultimateframedata.com/greninja.php",
    "hero" : "https://ultimateframedata.com/hero.php",
    "bullshit" : "https://ultimateframedata.com/hero.php",
    "ice climbers" : "https://ultimateframedata.com/ice_climbers.php",
    "icies" : "https://ultimateframedata.com/ice_climbers.php",
    "the climbers" : "https://ultimateframedata.com/ice_climbers.php",
    "nana" : "https://ultimateframedata.com/ice_climbers.php",
    "popo" : "https://ultimateframedata.com/ice_climbers.php",
    "ike" : "https://ultimateframedata.com/ike.php",
    "incineroar" : "https://ultimateframedata.com/incineroar.php",
    "incin" : "https://ultimateframedata.com/incineroar.php",
    "inkling" : "https://ultimateframedata.com/inkling.php",
    "isabelle" : "https://ultimateframedata.com/isabelle.php",
    "jigglypuff" : "https://ultimateframedata.com/jigglypuff.php",
    "jigs" : "https://ultimateframedata.com/jigglypuff.php",
    "jiggs" : "https://ultimateframedata.com/jigglypuff.php",
    "puff" : "https://ultimateframedata.com/jigglypuff.php",
    "joker" : "https://ultimateframedata.com/joker.php",
    "aresene" : "https://ultimateframedata.com/joker.php",
    "ken" : "https://ultimateframedata.com/ken.php",
    "king dedede" : "https://ultimateframedata.com/king_dedede.php",
    "dedede" : "https://ultimateframedata.com/king_dedede.php",
    "ddd" : "https://ultimateframedata.com/king_dedede.php",
    "d3" : "https://ultimateframedata.com/king_dedede.php",
    "king k. rool" : "https://ultimateframedata.com/king_k_rool.php",
    "k. rool" : "https://ultimateframedata.com/king_k_rool.php",
    "k rool" : "https://ultimateframedata.com/king_k_rool.php",
    "kirby" : "https://ultimateframedata.com/kirby.php",
    "link" : "https://ultimateframedata.com/link.php",
    "little mac" : "https://ultimateframedata.com/little_mac.php",
    "mac" : "https://ultimateframedata.com/little_mac.php",
    "lucario" : "https://ultimateframedata.com/lucario.php",
    "lucas" : "https://ultimateframedata.com/lucas.php",
    "lucina" : "https://ultimateframedata.com/lucina.php",
    "luigi" : "https://ultimateframedata.com/luigi.php",
    "mario" : "https://ultimateframedata.com/mario.php",
    "marth" : "https://ultimateframedata.com/marth.php",
    "mega man" : "https://ultimateframedata.com/mega_man.php",
    "megaman" : "https://ultimateframedata.com/mega_man.php",
    "meta knight" : "https://ultimateframedata.com/meta_knight.php",
    "metaknight" : "https://ultimateframedata.com/meta_knight.php",
    "mk" : "https://ultimateframedata.com/meta_knight.php",
    "mewtwo" : "https://ultimateframedata.com/mewtwo.php",
    "mew2" : "https://ultimateframedata.com/mewtwo.php",
    "m2" : "https://ultimateframedata.com/mewtwo.php",
    "mii brawler" : "https://ultimateframedata.com/mii_brawler.php",
    "brawler" : "https://ultimateframedata.com/mii_brawler.php",
    "mii gunner" : "https://ultimateframedata.com/mii_gunner.php",
    "gunner" : "https://ultimateframedata.com/mii_gunner.php",
    "sans" : "https://ultimateframedata.com/mii_gunner.php",
    "mii swordfighter" : "https://ultimateframedata.com/mii_swordfighter.php",
    "mii sword" : "https://ultimateframedata.com/mii_swordfighter.php",
    "swordfighter" : "https://ultimateframedata.com/mii_swordfighter.php",
    "mr.game and watch" : "https://ultimateframedata.com/mr_game_and_watch.php",
    "game and watch" : "https://ultimateframedata.com/mr_game_and_watch.php",
    "game & watch" : "https://ultimateframedata.com/mr_game_and_watch.php",
    "gnw" : "https://ultimateframedata.com/mr_game_and_watch.php",
    "g&w" : "https://ultimateframedata.com/mr_game_and_watch.php",
    "ness" : "https://ultimateframedata.com/ness.php",
    "olimar" : "https://ultimateframedata.com/olimar.php",
    "pac man" : "https://ultimateframedata.com/pac_man.php",
    "pac-man" : "https://ultimateframedata.com/pac_man.php",
    "pacman" : "https://ultimateframedata.com/pac_man.php",
    "pac" : "https://ultimateframedata.com/pac_man.php",
    "palutena" : "https://ultimateframedata.com/palutena.php",
    "palu" : "https://ultimateframedata.com/palutena.php",
    "peach" : "https://ultimateframedata.com/peach.php",
    "pichu" : "https://ultimateframedata.com/pichu.php",
    "pikachu" : "https://ultimateframedata.com/pikachu.php",
    "pika" : "https://ultimateframedata.com/pikachu.php",
    "piranha plant" : "https://ultimateframedata.com/piranha_plant.php",
    "plant" : "https://ultimateframedata.com/piranha_plant.php",
    "pit" : "https://ultimateframedata.com/pit.php",
    "squirtle" : "https://ultimateframedata.com/pt_squirtle.php",
    "ivysaur" : "https://ultimateframedata.com/pt_ivysaur.php",
    "ivy" : "https://ultimateframedata.com/pt_ivysaur.php",
    "charizard" : "https://ultimateframedata.com/pt_charizard.php",
    "zard" : "https://ultimateframedata.com/pt_charizard.php",
    "richter" : "https://ultimateframedata.com/richter.php",
    "belmont" : "https://ultimateframedata.com/richter.php",
    "ridley" : "https://ultimateframedata.com/ridley.php",
    "rob" : "https://ultimateframedata.com/rob.php",
    "robin" : "https://ultimateframedata.com/robin.php",
    "rosalina and luma" : "https://ultimateframedata.com/rosalina_and_luma.php",
    "rosalina" : "https://ultimateframedata.com/rosalina_and_luma.php",
    "rosa" : "https://ultimateframedata.com/rosalina_and_luma.php",
    "roy" : "https://ultimateframedata.com/roy.php",
    "ryu" : "https://ultimateframedata.com/ryu.php",
    "samus" : "https://ultimateframedata.com/samus.php",
    "sheik" : "https://ultimateframedata.com/sheik.php",
    "shulk" : "https://ultimateframedata.com/shulk.php",
    "simon" : "https://ultimateframedata.com/simon.php",
    "snake" : "https://ultimateframedata.com/snake.php",
    "sonic" : "https://ultimateframedata.com/sonic.php",
    "terry" : "https://ultimateframedata.com/terry.php",
    "toon link" : "https://ultimateframedata.com/toon_link.php",
    "tink" : "https://ultimateframedata.com/toon_link.php",
    "villager" : "https://ultimateframedata.com/villager.php",
    "villy" : "https://ultimateframedata.com/villager.php",
    "wario" : "https://ultimateframedata.com/wario.php",
    "wii fit trainer" : "https://ultimateframedata.com/wii_fit_trainer.php",
    "wii fit" : "https://ultimateframedata.com/wii_fit_trainer.php",
    "wft" : "https://ultimateframedata.com/wii_fit_trainer.php",
    "wolf" : "https://ultimateframedata.com/wolf.php",
    "yoshi" : "https://ultimateframedata.com/yoshi.php",
    "yound link" : "https://ultimateframedata.com/young_link.php",
    "yink" : "https://ultimateframedata.com/young_link.php",
    "zelda" : "https://ultimateframedata.com/zelda.php",
    "zero suit samus" : "https://ultimateframedata.com/zero_suit_samus.php",
    "zero suit" : "https://ultimateframedata.com/zero_suit_samus.php",
    "zss" : "https://ultimateframedata.com/zero_suit_samus.php"
}